### ISSUE TITLE
The RemoveFirst function has disappeared

### ISSUE THREAD

**Issue by engi** [Dennis1000/verysimplexml#6]
Hi,
I was using RS 10.1 Berlin with VerySimpleXML 2.0.3.
I updated RadStudio to version 10.3.2 Rio and and a bug appeared in VerySimpleXML.
With VerySimpleXML 2.0.5, the bug has been fixed but the IsSame function has been edited : now, it no longer removes the possible prefix in the name of the parsed node.
Is there a reason why the RemoveFirst function has been removed?

**Comment by Dennis1000** [comment]
I'm not quite sure what you mean ... which RemoveFirst function are you talking about?

**Comment by engi** [comment]
Originally, I didn't download the files from your github. I think the ones I had had been customized.
I added the RemoveFirst function in the source code of the new version (as internal function of IsSame function) and everything works fine. It permits to delete tag prefix, especially in onvif xml answers : `<env:body>` become `<body>.`
knowing that the prefix can change from one answer to another, it is convenient to remove it to do research on a specific tag

Sorry for the inconvenience

Here is my code :

function TXmlVerySimple.IsSame(const Value1, Value2: String): Boolean;
  function RemoveFirst(const DName: String): String;
  Var
    i: integer;
  begin
    Result := DName;
    i := Pos(':', DName);
    if i <> 0 then
    begin
      System.Delete(Result, 1, i);
    end;
  end;
begin
  if doCaseInsensitive in Options then
    Result := AnsiSameText(RemoveFirst(Value1), Value2)
  else
    Result := (RemoveFirst(Value1) = Value2);
end;

**Comment by Dennis1000** [comment]
:-)
btw: looks like I've forgotten to declare that IsSame function as _virtual_, this will be fixed in the next version. You may then just create your own 

TMyXmlVerySimple = class(TXmlVerySimple)
  function TXmlVerySimple.IsSame(const Value1, Value2: String): Boolean; override

and include your RemoveFirst there

**Comment by gmnevton** [comment]
I think, that Engi was using my version of lib. There is something like this:
```
function TXmlVerySimple.IsSame(const Value1, Value2: String): Boolean;
var
  prefix1, val1, prefix2, val2: String;
begin
  TXmlNode.GetNameAndPrefix(Value1, val1, prefix1);
  TXmlNode.GetNameAndPrefix(Value2, val2, prefix2);

  if doCaseInsensitive in Options then
    Result := ((CompareText(Value1, Value2) = 0) or ((doSearchExcludeNamespacePrefix in Options) and (CompareText(val1, val2) = 0)))
  else
    Result := ((Value1 = Value2) or ((doSearchExcludeNamespacePrefix in Options) and (val1 = val2)));
end;
```
or
```
function TXmlNode.IsSame(const Value1, Value2: String): Boolean;
var
  prefix1, val1, prefix2, val2: String;
begin
  GetNameAndPrefix(Value1, val1, prefix1);
  GetNameAndPrefix(Value2, val2, prefix2);

  Result := ((Assigned(Document) and Document.IsSame(val1, val2)) or // use the documents text comparison
    ((not Assigned(Document)) and (val1 = val2))); // or if not Assigned then compare names case sensitive
end;
```
and this:
```
function TXmlNodeList.IsSame(const Value1, Value2: String): Boolean;
begin
  Result := ((Assigned(Document) and Document.IsSame(Value1, Value2)) or // use the documents text comparison
            ((not Assigned(Document)) and (Value1 = Value2))); // or if not Assigned then compare names case sensitive
end;
```
where there is no need to use any hacks like "RemoveFirst", just use options `doSearchExcludeNamespacePrefix` to switch on or off the desired behavior of comparison.

**Comment by Dennis1000** [comment]
@gmnevton ah I see you've added a ton of stuff - like xpath and NamespacePrefixes, very very nice.

@engi so you just need to use @gmnevton's version with the above mentioned settings.
